[package]
name = "openshield-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
openshield-core = { version = "=0.1.25", path = "../openshield-core" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
chrono.workspace = true
ipnet.workspace = true

[lints]
workspace = true
