[package]
name = "openshield-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
crossterm.workspace = true
ipnet.workspace = true
nix.workspace = true
openshield-core = { version = "=0.1.7", path = "../openshield-core" }
openshield-protocol = { version = "=0.1.7", path = "../openshield-protocol" }
ratatui.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
chrono.workspace = true

[lints]
workspace = true
